In [2]:
import pandas as pd

df = pd.read_csv('https://storage.googleapis.com/kagglesdsdata/datasets/2088925/3469842/students_adaptability_level_online_education.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20240103%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240103T011756Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=350743d69f8d6c05e4f6edb34a57a81f9f9564ba0bd4c1d7310524feca7420228dd3c42c7196f5bff9f2b459df469d9f0fa6081f39eaec2e07b943c61cd33066387d5d9b8acf4d827e32b945b2d48105e043402941cf8e867389a6953704a2b3662eac84a6b05612e90f5fcb0fb4c8f9ffde500a1ba1928b20a1637510e3984af1cbe476703cd44f5c1dd909d4ec48daa1a935d1fd223f17e8e1ac4c5048c69b366fe7ac8df1d8696565286f6065ddd9b5515bd5552eb8b3816d25fba6abb529d2c12f12ebe59f61536f3d7692b2447811b4a38731016c6c12a591e24f53d0b080d62a8bd6dc7a7645ca7629d726be66e0b0ce3fded13ad5e40d5973b9790e5e')
df

,Gender,Age,Education Level,Institution Type,IT Student,Location,Load-shedding,Financial Condition,Internet Type,Network Type,Class Duration,Self Lms,Device,Adaptivity Level
0,Boy,21-25,University,Non Government,No,Yes,Low,Mid,Wifi,4G,3-6,No,Tab,Moderate
1,Girl,21-25,University,Non Government,No,Yes,High,Mid,Mobile Data,4G,1-3,Yes,Mobile,Moderate
2,Girl,16-20,College,Government,No,Yes,Low,Mid,Wifi,4G,1-3,No,Mobile,Moderate
3,Girl,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,4G,1-3,No,Mobile,Moderate
4,Girl,16-20,School,Non Government,No,Yes,Low,Poor,Mobile Data,3G,0,No,Mobile,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,Girl,16-20,College,Non Government,No,Yes,Low,Mid,Wifi,4G,1-3,No,Mobile,Low
1201,Girl,16-20,College,Non Government,No,No,High,Mid,Wifi,4G,3-6,No,Mobile,Moderate
1202,Boy,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,3G,1-3,No,Mobile,Moderate
1203,Girl,16-20,College,Non Government,No,No,Low,Mid,Wifi,4G,1-3,No,Mobile,Low
1204,Girl,11-15,School,Non Government,No,Yes,Low,Poor,Mobile Data,3G,1-3,No,Mobile,Moderate

In [3]:
y = df['Adaptivity Level']
y

0       Moderate
1       Moderate
2       Moderate
3       Moderate
4            Low
          ...
1200         Low
1201    Moderate
1202    Moderate
1203         Low
1204    Moderate
Name: Adaptivity Level, Length: 1205, dtype: object

In [4]:
X = df.drop('Adaptivity Level', axis=1)
X

,Gender,Age,Education Level,Institution Type,IT Student,Location,Load-shedding,Financial Condition,Internet Type,Network Type,Class Duration,Self Lms,Device
0,Boy,21-25,University,Non Government,No,Yes,Low,Mid,Wifi,4G,3-6,No,Tab
1,Girl,21-25,University,Non Government,No,Yes,High,Mid,Mobile Data,4G,1-3,Yes,Mobile
2,Girl,16-20,College,Government,No,Yes,Low,Mid,Wifi,4G,1-3,No,Mobile
3,Girl,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,4G,1-3,No,Mobile
4,Girl,16-20,School,Non Government,No,Yes,Low,Poor,Mobile Data,3G,0,No,Mobile
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,Girl,16-20,College,Non Government,No,Yes,Low,Mid,Wifi,4G,1-3,No,Mobile
1201,Girl,16-20,College,Non Government,No,No,High,Mid,Wifi,4G,3-6,No,Mobile
1202,Boy,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,3G,1-3,No,Mobile
1203,Girl,16-20,College,Non Government,No,No,Low,Mid,Wifi,4G,1-3,No,Mobile
1204,Girl,11-15,School,Non Government,No,Yes,Low,Poor,Mobile Data,3G,1-3,No,Mobile

In [20]:
from sklearn.model_selection import train_test_split
# Assuming X_train has categorical features
X_train_encoded = pd.get_dummies(X_train)

# Assuming X_test has categorical features
X_test_encoded = pd.get_dummies(X_test)

# Align columns to ensure the same set of features in both sets
X_test_encoded = X_test_encoded.reindex(columns=X_train_encoded.columns, fill_value=0)

# Make predictions on the testing data
y_pred = clf.predict(X_test_encoded)

# Assuming X is your feature matrix and y is your target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

X_train

,Gender,Age,Education Level,Institution Type,IT Student,Location,Load-shedding,Financial Condition,Internet Type,Network Type,Class Duration,Self Lms,Device
509,Girl,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,4G,1-3,No,Mobile
697,Boy,21-25,University,Non Government,Yes,Yes,Low,Mid,Wifi,3G,3-6,Yes,Computer
44,Boy,21-25,University,Non Government,Yes,Yes,Low,Mid,Wifi,3G,3-6,Yes,Computer
146,Boy,21-25,University,Non Government,Yes,Yes,High,Poor,Wifi,3G,3-6,No,Computer
972,Girl,26-30,University,Government,No,Yes,Low,Mid,Wifi,4G,0,No,Mobile
...,...,...,...,...,...,...,...,...,...,...,...,...,...
802,Boy,11-15,School,Non Government,No,Yes,High,Mid,Wifi,4G,1-3,No,Computer
53,Boy,26-30,University,Government,Yes,No,Low,Poor,Mobile Data,4G,1-3,No,Mobile
350,Girl,1-5,School,Non Government,No,Yes,Low,Poor,Mobile Data,4G,1-3,No,Mobile
79,Boy,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,4G,1-3,No,Mobile
792,Girl,11-15,School,Government,No,No,Low,Mid,Mobile Data,3G,0,No,Mobile

In [21]:
from sklearn.model_selection import train_test_split
# Assuming X_train has categorical features
X_train_encoded = pd.get_dummies(X_train)

# Assuming X_test has categorical features
X_test_encoded = pd.get_dummies(X_test)

# Align columns to ensure the same set of features in both sets
X_test_encoded = X_test_encoded.reindex(columns=X_train_encoded.columns, fill_value=0)

# Make predictions on the testing data
y_pred = clf.predict(X_test_encoded)

# Assuming X is your feature matrix and y is your target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)
X_test

,Gender,Age,Education Level,Institution Type,IT Student,Location,Load-shedding,Financial Condition,Internet Type,Network Type,Class Duration,Self Lms,Device
1137,Girl,21-25,University,Non Government,No,No,Low,Mid,Wifi,4G,1-3,No,Mobile
685,Girl,16-20,College,Non Government,No,No,Low,Mid,Wifi,4G,1-3,No,Mobile
1115,Girl,11-15,School,Non Government,No,Yes,Low,Poor,Mobile Data,3G,1-3,No,Mobile
970,Girl,11-15,School,Government,No,Yes,Low,Rich,Wifi,4G,1-3,No,Mobile
31,Girl,16-20,College,Non Government,No,No,Low,Mid,Mobile Data,4G,1-3,No,Mobile
...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,Boy,21-25,University,Non Government,Yes,Yes,High,Poor,Wifi,4G,1-3,Yes,Computer
845,Boy,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,4G,1-3,No,Mobile
789,Girl,21-25,University,Non Government,No,Yes,Low,Mid,Wifi,4G,3-6,No,Computer
370,Boy,16-20,School,Government,No,Yes,Low,Mid,Wifi,4G,1-3,No,Mobile
463,Boy,21-25,University,Non Government,No,Yes,Low,Poor,Mobile Data,4G,1-3,Yes,Mobile

In [22]:
from sklearn.model_selection import train_test_split
# Assuming X_train has categorical features
X_train_encoded = pd.get_dummies(X_train)

# Assuming X_test has categorical features
X_test_encoded = pd.get_dummies(X_test)

# Align columns to ensure the same set of features in both sets
X_test_encoded = X_test_encoded.reindex(columns=X_train_encoded.columns, fill_value=0)

# Make predictions on the testing data
y_pred = clf.predict(X_test_encoded)

# Assuming X is your feature matrix and y is your target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)
y_train

509    Moderate
697         Low
44          Low
146    Moderate
972         Low
         ...
802         Low
53     Moderate
350    Moderate
79     Moderate
792         Low
Name: Adaptivity Level, Length: 964, dtype: object

In [23]:
from sklearn.model_selection import train_test_split
# Assuming X_train has categorical features
X_train_encoded = pd.get_dummies(X_train)

# Assuming X_test has categorical features
X_test_encoded = pd.get_dummies(X_test)

# Align columns to ensure the same set of features in both sets
X_test_encoded = X_test_encoded.reindex(columns=X_train_encoded.columns, fill_value=0)

# Make predictions on the testing data
y_pred = clf.predict(X_test_encoded)

# Assuming X is your feature matrix and y is your target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)
y_test

1137    Moderate
685          Low
1115         Low
970     Moderate
31           Low
          ...
490         High
845     Moderate
789     Moderate
370     Moderate
463         High
Name: Adaptivity Level, Length: 241, dtype: object

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Load the dataset
file_path = 'students_adaptability_level_online_education.csv'
df = pd.read_csv(file_path)

# Identify the target variable and features
X = df.drop('Adaptivity Level', axis=1)  # Features
y = df['Adaptivity Level']  # Target variable

# Handle categorical features using one-hot encoding
categorical_cols = [col for col in X.columns if X[col].dtype == 'object']
preprocessor = ColumnTransformer(
    transformers=[('cat', OneHotEncoder(), categorical_cols)],
    remainder='passthrough'
)

X = preprocessor.fit_transform(X)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and fit the FastTree model
model = HistGradientBoostingClassifier(random_state=42)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print the results
print(f'Accuracy: {accuracy}')
print('Classification Report:\n', classification_rep)

Accuracy: 0.9128630705394191
Classification Report:
               precision    recall  f1-score   support

        High       0.88      0.65      0.75        23
         Low       0.93      0.94      0.94       103
    Moderate       0.90      0.94      0.92       115

    accuracy                           0.91       241
   macro avg       0.91      0.84      0.87       241
weighted avg       0.91      0.91      0.91       241

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Load the dataset
file_path = 'students_adaptability_level_online_education.csv'
df = pd.read_csv(file_path)

# Identify the target variable and features
X = df.drop('Adaptivity Level', axis=1)  # Features
y = df['Adaptivity Level']  # Target variable

# Handle categorical features using one-hot encoding
categorical_cols = [col for col in X.columns if X[col].dtype == 'object']
preprocessor = ColumnTransformer(
    transformers=[('cat', OneHotEncoder(), categorical_cols)],
    remainder='passthrough'
)

# Split the dataset into training and testing sets for each random state
results_list = []

for random_state_val in range(1, 10001):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=random_state_val)

    # Preprocess the data
    X_train = preprocessor.fit_transform(X_train)
    X_test = preprocessor.transform(X_test)

    # Initialize and fit the FastTree model
    model = HistGradientBoostingClassifier(random_state=random_state_val)
    model.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred, output_dict=True)

    # Append the results to the list
    results_dict = {
        'Random State': random_state_val,
        'Accuracy': accuracy,
        'Classification Report': classification_rep
    }
    results_list.append(results_dict)

# Create a DataFrame from the list of results
results_df = pd.DataFrame(results_list)

# Save the compiled outcomes to a CSV file
results_df.to_csv('compiled_results_fasttree.csv', index=True)